// types that are frequently reused are defined here
export type ColorOptions =
  | 'primary'
  | 'primary-dark'
  | 'secondary-dark'
  | 'secondary'
  | 'gray'
  | 'dark-gray'
  | 'white'
  | 'black'
  | 'pink'
  | 'green'
  | 'red'
  | 'yellow'
  | 'orange'
  | 'blue'
  | 'teal'
  | 'indigo'
  | 'purple'
export type SizeOptions = 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | '2xlarge' | '3xlarge' | '4xlarge'
